server:
  port: 8082

#  spring:
#    jackson:
#      serialization: write-dates-as-timestamps=false
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: nikita
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    liquibase-schema: app
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true

security:
  jwt:
    secret: c3VwZXJwdXBlcmR1cGVybWVnYWhhcmRvdmVydG9waGlnaHNlY3JldA==
    access: 3600000
    refresh: 2592000000